name: Logicrux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      env:
        TOKEN_OG: ${{ secrets.TOKEN_OG }}
      run: |
        npm install
        npx tsc
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "logicrux"
        heroku_email: "mariodavo.20@gmail.com"
