name: Logicrux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.3.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      env:
        TOKEN_OG: ${{ secrets.TOKEN_OG }}
      run: |
        npm install
        npx tsc
